### ISSUE TITLE
OptimoveNotificationServiceExtension ARM compiler error

### ISSUE THREAD

**Issue by tpapazoglou-novi** [optimove-tech/iOS-SDK-Integration-Guide#94]
**Describe the bug**
Compiler error when trying to build with arm simulator.

When I'm using the `OptimoveNotificationServiceExtension` and trying to build my app with arm simulator, I'm getting `Could not find module 'OptimoveNotificationServiceExtension' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator` compiler error.

**To Reproduce**
1. Go to the target device and select 'iPhone 15 Pro' (not Rosetta)
2. Build app
3. See error

**Expected behavior**
Successfully build and run the app with ARM simulator and not Rosetta

**Environment (please complete the following information):**
 - OS: iOS 17.0.1
 - Version 5.5.0

**Comment by eligutovsky** [comment]
Hello @tpapazoglou,
Could you elaborate on your environment (macos version, xcode version) and how you consume the SDK (cocoapods, SPM)?

**Comment by tpapazoglou-novi** [comment]
Hello @eligutovsky,

Yes, of course!

macOS Sonoma 14.1.2
Xcode 15.0.1
SPM

**Comment by eligutovsky** [comment]
I have created a new project. Added and imported the Optimove iOS SDK version 5.5.0. This issue is not reproduced on macOS 14.1.1 with Xcode 15.0.1

Could you please share your app's Build Settings?

<img width="1285" alt="Screenshot 2023-12-12 at 3 38 17" src="https://github.com/optimove-tech/Optimove-SDK-iOS/assets/9871129/6877f7d1-2a68-4c3d-a8c3-755015815b31">

<img width="1285" alt="Screenshot 2023-12-12 at 3 28 32" src="https://github.com/optimove-tech/Optimove-SDK-iOS/assets/9871129/f15f6acf-4be3-4135-97df-952a85d92ec4">

**Comment by tpapazoglou-novi** [comment]
Based on your screenshots, I had to delete some excluded architectures and now it builds successfully.

Thank you so much for your help.
